// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDp3Y44H3CqsuzbJZ7nJueJ6aEzP6Gk8',
    appId: '1:566577271953:android:361c5346841066abdd1b30',
    messagingSenderId: '566577271953',
    projectId: 'ticketorium-project',
    storageBucket: 'ticketorium-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ecQP93gv8e8_IZT2a8CrW9h3b6A-Jzc',
    appId: '1:566577271953:ios:4a4dbd29cf42e53edd1b30',
    messagingSenderId: '566577271953',
    projectId: 'ticketorium-project',
    storageBucket: 'ticketorium-project.appspot.com',
    iosBundleId: 'com.example.ticketoriumAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ecQP93gv8e8_IZT2a8CrW9h3b6A-Jzc',
    appId: '1:566577271953:ios:4a4dbd29cf42e53edd1b30',
    messagingSenderId: '566577271953',
    projectId: 'ticketorium-project',
    storageBucket: 'ticketorium-project.appspot.com',
    iosBundleId: 'com.example.ticketoriumAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9U2vZnLsO9-hSpLULTSuonFRz2RTxsUQ',
    appId: '1:566577271953:web:208d886a3a6ab1bedd1b30',
    messagingSenderId: '566577271953',
    projectId: 'ticketorium-project',
    authDomain: 'ticketorium-project.firebaseapp.com',
    storageBucket: 'ticketorium-project.appspot.com',
    measurementId: 'G-XT886NWKQ3',
  );
}
